name: Upload Google Sites to Drive

on:
  schedule:
    - cron: '* * * * *'  # 毎分実行
  workflow_dispatch:

jobs:
  upload_to_drive:
    runs-on: ubuntu-latest

    steps:
    # Step 1: リポジトリの内容をチェックアウト
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Pythonのセットアップ
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # Step 3: 必要なライブラリをインストール
    - name: Install dependencies
      run: |
        pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

    # Step 4: Google Sitesの内容をwgetでダウンロード
    - name: Download Google Sites content (using wget)
      env:
        GOOGLE_SITES_URL: ${{ secrets.GOOGLESITES_URL }}  # GitHub SecretsからURLを取得
      run: |
        # wgetを使ってGoogle Sitesからサイトをダウンロード
        echo "Downloading site from $GOOGLE_SITES_URL"
        mkdir -p downloaded_site
        wget -r -np -nH --cut-dirs=1 -R "index.html*" $GOOGLE_SITES_URL -P ./downloaded_site

    # Step 5: Google Driveにアップロード
    - name: Upload to Google Drive
      env:
        GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}  # Google DriveのフォルダID
        GOOGLE_CREDENTIALS_JSON: ${{ secrets.GDRIVE_CREDENTIALS_JSON }}  # Google Drive APIの認証情報
      run: |
        # ダウンロードしたGoogle Sitesの内容をGoogle Driveにアップロード
        python upload_to_drive.py
