jobs:
  selenium_setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          # Install selenium and chromium dependencies
          pip install selenium
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          
          # Get the version of Chromium
          CHROMIUM_VERSION=$(chromium-browser --version | awk '{print $2}')
          echo "Chromium version is $CHROMIUM_VERSION"
          
          # Get the corresponding chromedriver version for that Chromium version
          DRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROMIUM_VERSION%.*})
          echo "Chromedriver version is $DRIVER_VERSION"
          
          # Download and install chromedriver
          wget https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Download site with Selenium
        run: |
          python download_site_selenium.py

      - name: Upload to Google Drive and Update GitHub
        run: |
          python upload_to_drive.py
