name: Upload Google Sites to Drive

on:
  schedule:
    - cron: '*/5 * * * *'  # 5分おきに実行
  workflow_dispatch:

jobs:
  upload_to_drive:
    runs-on: ubuntu-latest

    steps:
    # Step 1: リポジトリの内容をチェックアウト
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Pythonのセットアップ
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    # Step 3: 必要なライブラリをインストール
    - name: Install dependencies
      run: |
        pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

    # Step 4: Google Sitesの内容をwgetでダウンロード
    - name: Download Google Sites content (using wget)
      env:
        GOOGLE_SITES_URL: ${{ secrets.GOOGLESITES_URL }}  # GitHub SecretsからURLを取得
      run: |
        # wgetを使ってGoogle Sitesからサイトをダウンロード
        echo "Downloading site from $GOOGLE_SITES_URL"
        mkdir -p downloaded_site
        wget -r -np -nH --cut-dirs=1 -R "index.html*" $GOOGLE_SITES_URL -P ./downloaded_site

    # Step 4.5: ダウンロードしたサイトをZIP化
    - name: Zip downloaded site
      run: |
        cd downloaded_site
        zip -r ../site.zip .

    # Step 5: Google Driveにアップロード
    - name: Upload to Google Drive
      env:
        GDRIVE_CREDENTIALS_JSON: ${{ secrets.GDRIVE_CREDENTIALS_JSON }}  # GitHub Secretsからcredentials.jsonを取得
      run: |
        python upload_to_drive.py

    - name: Check site.zip
      run: |
        ls -lh site.zip || echo "site.zip が見つかりません"
