name: Upload Google Sites to Drive

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  upload_to_drive:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

    - name: Download Google Sites content (using wget)
      env:
        GOOGLE_SITES_URL: ${{ secrets.GOOGLESITES_URL }}
        GDRIVE_FOLDER_ID:   ${{ secrets.GDRIVE_FOLDER_ID }}
      run: |
        echo "Downloading site from $GOOGLE_SITES_URL"
        mkdir -p downloaded_site
        wget -r -np -nH --cut-dirs=1 -R "index.html*" $GOOGLE_SITES_URL -P ./downloaded_site

    - name: Zip downloaded site
      run: |
        cd downloaded_site
        zip -r ../site.zip .

    - name: Upload to Google Drive
      env:
        GDRIVE_CREDENTIALS_JSON: ${{ secrets.GDRIVE_CREDENTIALS_JSON }}
        GDRIVE_FOLDER_ID:         ${{ secrets.GDRIVE_FOLDER_ID }}
      run: |
        python upload_to_drive.py

    - name: Check site.zip
      run: |
        ls -lh site.zip || echo "site.zip が見つかりません"
