name: Upload Google Sites to Drive

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  selenium_setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install selenium
          sudo apt-get install -y chromium-browser
          sudo apt-get install -y chromedriver

      - name: Download site with Selenium
        run: |
          python download_site_selenium.py

      - name: Create zip file
        run: |
          zip -r site.zip downloaded_site

      - name: Upload zip to Google Drive
        run: |
          python upload_to_drive.py

      - name: Update latest.txt in GitHub repository
        run: |
          python update_latest_txt.py
